//
//  ChatGPT_OC_Clone-Swift.h
//  ChatGPT-OC-Clone
//
//  Generated by Swift compiler
//

#ifndef ChatGPT_OC_Clone_Swift_h
#define ChatGPT_OC_Clone_Swift_h

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

@class UIViewController;
@class NSString;
@class NSArray;

NS_ASSUME_NONNULL_BEGIN

// MARK: - ChatMessage
@interface ChatMessage : NSObject
@property (nonatomic, strong) NSString *id;
@property (nonatomic, strong) NSString *content;
@property (nonatomic, assign) BOOL isFromUser;
@property (nonatomic, strong) NSDate *timestamp;
- (instancetype)initWithId:(NSString *)id content:(NSString *)content isFromUser:(BOOL)isFromUser timestamp:(NSDate *)timestamp;
@end

// MARK: - ChatViewModel
@interface ChatViewModel : NSObject
@property (nonatomic, readonly) NSArray *messages;
@property (nonatomic, assign) BOOL isInteracting;
@property (nonatomic, strong) NSString *typingText;
- (instancetype)init;
- (void)addMessage:(ChatMessage *)message;
- (void)removeMessageAtIndex:(NSInteger)index;
- (void)updateLastMessageWithContent:(NSString *)content;
- (void)setInteracting:(BOOL)interacting;
- (void)startStreamingResponseFor:(NSString *)userMessage;
- (void)updateStreamingResponse:(NSString *)content;
- (void)finishStreamingResponse;
- (void)clearMessages;
@end

// MARK: - ChatSwiftUIViewWrapper
@interface ChatSwiftUIViewWrapper : UIViewController
@property (nonatomic, strong) ChatViewModel *viewModel;
+ (ChatSwiftUIViewWrapper *)createWrapperWithViewModel:(ChatViewModel *)viewModel;
- (void)scrollToBottomWithAnimated:(BOOL)animated;
@end

NS_ASSUME_NONNULL_END

#endif /* ChatGPT_OC_Clone_Swift_h */

